name: CI

on:
  workflow_call:
  push:
    branches:
      - main
      - dev
    tags-ignore:
      - '**'
    paths-ignore:
      - '**.md'
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: pnpm

      - name: 📥 Install deps
        run: pnpm install --frozen-lockfile

      - name: 🏗 Build
        run: pnpm build

      - name: 🔍 Typecheck
        run: pnpm typecheck

      - name: 🔬 Lint
        run: pnpm lint

      # - name: 🧪 Run tests
      #   run: pnpm test
