name: 🚀 Deploy
on:
  workflow_dispatch:
  workflow_run:
    workflows: [CI]
    types:
      - completed
    branches: [dev]

permissions:
  contents: read
  packages: write

run-name: 🚀 Deploy (${{ github.ref_name }})

jobs:
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    if: ${{ (github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch') && github.repository_owner == 'Happy-Times-Gaming' }}
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🔢 Get HEAD commit hash
        id: get_head_hash
        run: echo "HEAD_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: docker-meta
        uses: docker/metadata-action@v5
        with:
          flavor: |
            latest=false
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            GIT_HASH=${{ steps.get_head_hash.outputs.HEAD_HASH }}

      - name: Trigger Deploy Webhook
        run: |
          curl --request GET '${{ secrets.DEPLOY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}'
