name: 🔖 Release (dev)
on:
  # runs on dev
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      ref:
        description: The branch that is being released. Should be a branch on the given repository
        required: true
        type: choice
        default: dev
        options:
          - dev

jobs:
  release:
    if: ${{ github.repository_owner == 'Happy-Times-Gaming' }}
    uses: ./.github/workflows/shared-release.yaml
    secrets: inherit
    with:
      ref: ${{ inputs.ref || 'dev' }}
      prerelease: true
